# Generated by Django 4.1.3 on 2022-12-07 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_profilecertification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileeducation',
            options={'ordering': ['-final_date'], 'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
    ]
